### ISSUE TITLE
Unable to hide powerpoint window.

### ISSUE THREAD

**Issue by shouldsee** [matthewrenze/powerpoint-to-pdf#2]
How can I avoid showing a powerpoint dialog?

```python
powerpoint.Visible = 0
###pywintypes.com_error: (-2147352567, 'Exception occurred.', (0, 'Microsoft PowerPoint', 'Application.Visible : Invalid request.  Hiding the application window is not allowed.', '', 0, -2147188160), None)
```

**Comment by matthewrenze** [comment]
@shouldsee, 

I tested the script today and it appears to still be working correctly on my machine. So I'm guessing there is something specific to your machine that is preventing the script from completing successfully. 

The issue likely has to do with the line "powerpoint.Visible=1".

You may want to try using the "win32com" package instead of the "comtypes" package to see if that works:
https://github.com/mhammond/pywin32
https://odetocode.com/blogs/scott/archive/2013/06/26/convert-a-directory-of-powerpoint-slides-to-pdf-with-python.aspx

If that doesn't work, then one of these posts might be helpful in diagnosing the issue on your machine:
https://stackoverflow.com/questions/56538121/visible-property-of-power-point-application-in-win32com-under-python-is-not-work
https://stackoverflow.com/questions/27697408/interop-powerpoint-equivalent-of-interop-word-application-visiblity-off

Best of luck!

Matthew

**Comment by shouldsee** [comment]
> @shouldsee,
> 
> I tested the script today and it appears to still be working correctly on my machine. So I'm guessing there is something specific to your machine that is preventing the script from completing successfully.
> 
> The issue likely has to do with the line "powerpoint.Visible=1".
> 
> You may want to try using the "win32com" package instead of the "comtypes" package to see if that works:
> https://github.com/mhammond/pywin32
> https://odetocode.com/blogs/scott/archive/2013/06/26/convert-a-directory-of-powerpoint-slides-to-pdf-with-python.aspx
> 
> If that doesn't work, then one of these posts might be helpful in diagnosing the issue on your machine:
> https://stackoverflow.com/questions/56538121/visible-property-of-power-point-application-in-win32com-under-python-is-not-work
> https://stackoverflow.com/questions/27697408/interop-powerpoint-equivalent-of-interop-word-application-visiblity-off
> 
> Best of luck!
> 
> Matthew

Thank you Matthew, I can confirm that removing "powerpoint.Visible=1" statement enables a window-less convertion. My problem was caused by a powerpoint running in the background.
